# Generated by Django 6.0 on 2026-01-31 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'franchises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., MyAnimeList)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., mal)', unique=True)),
                ('category', models.CharField(choices=[('info', 'Information'), ('stream', 'Streaming')], max_length=10)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=10)),
            ],
            options={
                'ordering': ['-year', 'season'],
                'unique_together': {('year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Japanese title', max_length=200)),
                ('title_en', models.CharField(blank=True, help_text='English title (optional)', max_length=200)),
                ('aliases', models.TextField(blank=True, help_text='Alternative titles, one per line')),
                ('has_source', models.BooleanField(default=False, help_text='Whether the anime has source material (manga, LN, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='shows.franchise')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.season')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Episode number (allows OVA1, 0.5, etc.)', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('is_special', models.BooleanField(default=False, help_text='For OVAs, specials, etc.')),
                ('discussion_url', models.URLField(blank=True, help_text='Reddit discussion thread URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.show')),
            ],
            options={
                'ordering': ['show', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ShowLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show_links', to='shows.linktype')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='shows.show')),
            ],
            options={
                'unique_together': {('show', 'link_type')},
            },
        ),
    ]
