# Generated by Django 6.0 on 2026-01-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['show', 'order']},
        ),
        migrations.AddField(
            model_name='episode',
            name='order',
            field=models.IntegerField(default=0, help_text='Sort order (allows OVAs to be placed between episodes)'),
        ),
        migrations.AddField(
            model_name='show',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether the show is active (disable when completed)'),
        ),
    ]
