# Generated by Django 6.0 on 2026-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_episode_options_episode_order_show_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(blank=True, help_text='Air date and time', null=True),
        ),
    ]
