# Generated by Django 6.0 on 2026-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_episode_air_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
    ]
