# Generated by Django 6.0 on 2026-02-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_episode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='episode_count',
            field=models.IntegerField(blank=True, help_text='Total number of episodes (if known)', null=True),
        ),
    ]
