# Generated by Django 6.0 on 2026-02-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_add_episode_count_to_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='batch_release',
            field=models.BooleanField(default=False, help_text='Whether episodes are released in batches (e.g., Netflix)'),
        ),
    ]
