# Generated by Django 6.0 on 2026-02-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_add_batch_release_to_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('shows_scanned', models.IntegerField(default=0)),
                ('episodes_found', models.IntegerField(default=0)),
                ('episodes_posted', models.IntegerField(default=0)),
                ('episodes_skipped', models.IntegerField(default=0)),
                ('episodes_failed', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable scheduled scanning')),
                ('interval_minutes', models.IntegerField(default=2, help_text='Interval between scans in minutes')),
                ('last_run', models.DateTimeField(blank=True, help_text='Timestamp of the last scheduled scan', null=True)),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
                'verbose_name_plural': 'Scheduler Configuration',
            },
        ),
        migrations.CreateModel(
            name='ScanEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.CharField(max_length=20)),
                ('source', models.CharField(default='Nyaa', max_length=50)),
                ('torrent_title', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(blank=True)),
                ('found_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('found', 'Found'), ('eligible', 'Eligible'), ('posted', 'Posted'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='found', max_length=20)),
                ('status_reason', models.CharField(blank=True, help_text='Reason for status (e.g., why skipped)', max_length=200)),
                ('discussion_url', models.URLField(blank=True, help_text='Reddit discussion URL if posted')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_episodes', to='shows.show')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_episodes', to='shows.scanhistory')),
            ],
            options={
                'verbose_name': 'Scan Episode',
                'verbose_name_plural': 'Scan Episodes',
                'ordering': ['-scan__scan_time', 'show__title'],
            },
        ),
    ]
