# Generated by Django 6.0 on 2026-02-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_scanhistory_schedulerconfig_scanepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_enabled', models.BooleanField(default=False, help_text='Enable Discord webhook notifications')),
            ],
            options={
                'verbose_name': 'Notification Configuration',
                'verbose_name_plural': 'Notification Configuration',
            },
        ),
    ]
