# Generated by Django 6.0 on 2026-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_notificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='scheduled_for_removal',
            field=models.BooleanField(default=False, help_text="Whether this episode's thread has been removed from Reddit"),
        ),
    ]
