# Generated by Django 6.0 on 2026-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_episode_scheduled_for_removal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showlink',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
