# Generated by Django 6.0 on 2026-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_show_disable_nyaa_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerconfig',
            name='youtube_interval_minutes',
            field=models.IntegerField(default=5, help_text='Minimum minutes between YouTube scans (limits API quota usage)'),
        ),
        migrations.AddField(
            model_name='schedulerconfig',
            name='youtube_last_run',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last scheduled YouTube scan', null=True),
        ),
    ]
